### ISSUE TITLE
Possible to listen for scenes activations?

### ISSUE THREAD

**Issue by thundergreen** [azogue/eventsensor#2]
I have an idea where i need to create a sensor once a scene has been activated. Using the even call-service gives me this nice piece of code:

```
{
    "event_type": "call_service",
    "data": {
        "domain": "scene",
        "service": "turn_on",
        "service_data": {
            "entity_id": "scene.evening_light"
        }
    },
    "origin": "LOCAL",
    "time_fired": "2020-04-21T19:48:42.472930+00:00",
    "context": {
        "id": "bb8e9486138a4c45b0feda4386005a93",
        "parent_id": null,
        "user_id": "9f64f27b8c134e0aa5e8bd26ac59ff0a"
    }
}
```

Can i Use this also for the sensor and if how? :) Would highly be interested as THIS was exactly what I was looking for some days ogo :)

**Comment by azogue** [comment]
Hi @thundergreen,

That event filter is not possible with the current version, because of the _sub-filtering_ you need (filter events with a **nested dict** inside, like `{"service_data": {"entity_id": "scene.evening_light"}}`

I will try to make a fix for that kind of situation. The sensor aimed to filter simple events with just specific key: value pairs inside. To filter "call_service" for specific service_data, fine-grained filtering is needed.

Also, I just discovered a bug in the event filter: In https://github.com/azogue/eventsensor/blob/bcabeae58d7f79090a05b07096b7390e784d6dde/custom_components/eventsensor/sensor.py#L108
it should use `<=`, not `<`. I will also fix that.

**Comment by azogue** [comment]
@thundergreen, with the changes I'm doing right now, it will be possible to do what you want :)

In your case, the yaml would be:

```yaml
sensor:
  # Sensor to retain the last time a specific scene is turned on 
  - platform: eventsensor
    name: Last activation
    event: call_service
    state: service_data.entity_id
    event_data:
      domain: scene
      service: turn_on
      service_data:
        entity_id: scene.evening_light

  # Sensor to retain the last activated scene, with custom mapping for pretty states 
  - platform: eventsensor
    name: Last scene
    event: call_service
    state: service_data.entity_id
    event_data:
      domain: scene
      service: turn_on
    state_map:
      scene.evening_light: Evening
      scene.afternoon_light: Afternoon
      scene.other: Other scene
      # ...
```

The 1st sensor would look only to that specific scene, the 2nd one would update for any scene being turn_on, showing the scene as state.

<img width="371" alt="Last activation sensor" src="https://user-images.githubusercontent.com/9748301/79966728-263d5e80-848e-11ea-8022-6cb88bfa2b95.png">

<img width="372" alt="last scene sensor" src="https://user-images.githubusercontent.com/9748301/79966471-c47cf480-848d-11ea-83e4-9e56085d27b0.png">

I suppose the 2nd one is more useful, right?

BTW, thanks for your input here, this usage suggestion opens new possibilities for this sensor as a very useful **debug helper**.

**Wait a bit for the next release**, which enables UI configuration (and no more HA restarts) and makes this possible. 

A preview ;-)
<img width="1071" alt="preview_config_flow" src="https://user-images.githubusercontent.com/9748301/79967116-b7acd080-848e-11ea-8e4c-a1164e29df94.png">
