### ISSUE TITLE
expire status after x seconds

### ISSUE THREAD

**Issue by wivaku** [azogue/eventsensor#23]
Using eventsensor to track motion sensor events from my netatmo camera.  
Currently the state stays in the last detected motion.

Similar to [MQTT sensor](https://www.home-assistant.io/integrations/sensor.mqtt/), is it possible to expire the status after a while?

This so the state goes back to `off` after e.g. `10 seconds`.

**Comment by Fabenissimo** [comment]
I've worked around this via a binary sensor that turns off after a timeout you can specify:

```
binary_sensor:
  - platform: template
    sensors:
      netatmo_camera_garage_animal_detected:
        friendly_name: "Netatmo Camera Garage Tier erkannt"
        value_template: >-
          {% set foo = states('sensor.current_time_24hstring') %}
          {{ is_state('sensor.netatmo_camera_garage_animal', 'animal') and as_timestamp(now()) - as_timestamp(state_attr('sensor.netatmo_camera_garage_animal', 'time_fired')) <= states('input_number.netatmo_events_cooldown_time') | int }}
```
