### ISSUE TITLE
Time fired in state?

### ISSUE THREAD

**Issue by hvorragend** [azogue/eventsensor#36]
I am trying to create event sensors for homematic.keypress events. 

My problem is that I alway have PRESS_SHORT in my state. So that I cannot see if this entity has changed (the value). I just the the last change time. It does't make sense inside a logbook card. 😄

Is it possible store the event time in this new entity? I'be tried the following without success:

```
- platform: eventsensor
  name: Doorbell
  unique_id: eventsensor_doorbell
  event: homematic.keypress
  # state: param
  state: time_fired
  event_data:
    name: Doorbell
    param: PRESS_SHORT
    channel: 1
```

Or is it possible to clear the state content similar as "off_delay: 1" (see binary_sensor)?
