### ISSUE TITLE
No longer works with Hue remotes since 2012.12.0b0

### ISSUE THREAD

**Issue by ianfretwell** [azogue/eventsensor#38]
Apparently there are changes to the events/devices due to the move to the Hue API v2 that are introduced with the 2021.12 builds.
As per :- [https://github.com/home-assistant/core/pull/58996](url)

Currently this renders event-sensor unusable as it no longer seems to see the devices.

Are there any plans to support this going forward please?

**Comment by trancefam** [comment]
This does not directly answer your question about the future of this component, but I was able to eliminate my use of it by changing my remote button automations to use event triggers. To find out the details of the event, I went to Developer Tools -> Events and entered "hue_event" and clicked "Start Listening". Then I pushed the button on my hue remote and see:
![image](https://user-images.githubusercontent.com/26947075/145695867-20e2e25d-673a-40e3-8680-9b757144c290.png)


The important properties are highlighted.

I changed my automation from:

```yml
- alias: Remote - Living room dimmer
  trigger:
   -  platform: state
      entity_id:
       - sensor.hue_livingroom_remote
  action:
    - service: scene.turn_on
      data_template:
       entity_id: >
           {% set theSwitch = trigger.entity_id %}  
           {% if is_state(theSwitch, "1_click_up") %}
             scene.living_room_high
           {% elif is_state(theSwitch, "2_click_up") %}
             scene.living_room_medium
           {% elif is_state(theSwitch, "3_click_up") %}
             scene.living_room_low
           {% elif is_state(theSwitch, "4_click_up") %}
             scene.living_room_no_light
           {% endif %}
```

To:

```yml
- alias: Remote - Living room dimmer
  mode: restart
  trigger:
    - platform: event
      event_type: "hue_event"
      event_data:
        id: hue_livingroom_remote_button
        type: initial_press
    - platform: event
      event_type: "hue_event"
      event_data:
        id: hue_livingroom_remote_button
        type: short_release
  action:
    - service: scene.turn_on
      data:
        entity_id: >
          {% set theButton = trigger.event.data.subtype %} 
          {% if theButton == 1 %}
            scene.living_room_high
          {% elif theButton == 2 %}
            scene.living_room_medium
          {% elif theButton == 3 %}
            scene.living_room_low
          {% else %}
            scene.living_room_no_light
          {% endif %}
```

Note, during my testing I found that if I clicked different buttons very quickly, sometimes it did not send a "initial_press" event, only a "short_release", so I just added an additional trigger for that.
