### ISSUE TITLE
possible to combine state data?

### ISSUE THREAD

**Issue by GH2user** [azogue/eventsensor#7]
Hi,
I'm trying to use this with a xiaomi aqara cube using ZHA and it works just great in reporting flips and turns and stuff.
Now I wonder if I can combine more arguments into the final output for the state mapping.
Event received;
```
    "event_type": "zha_event",
    "data": {
        "device_ieee": "00:15:8d:00:04:21:53:9b",
        "unique_id": "00:15:8d:00:04:21:53:9b:2:0x0012",
        "endpoint_id": 2,
        "cluster_id": 18,
        "command": "flip",
        "args": {
            "value": 65,
            "flip_degrees": 90,
            "activated_face": 2
        }
```
Would like to combine the command "flip" and the argument " flip_degrees" or the "activated_face".
Sofar I have not used the state mapping at all.

thanks, Nico

**Comment by azogue** [comment]
Hi @GH2user,

Right now the state is formed by pointing just to one value in the event data, I'm not sure how to define compositions like the one you're looking for (any suggestion?)

I suppose the quickest way to achieve that is with 3 sensors: 2x event sensors for the "command" and "flip_degrees" and a third one, a `template sensor`, to combine both.
Or even **just 1 event sensor and 1 template sensor**, as all data is going to be available in the state attributes of the event sensor.

Anyway, I'm waiting for my own xiaomi aqara cube right now :), so in some weeks I'll be probably in the same point as you (I'm using the deconz integration instead of zha, but I suppose it's the same)

**Comment by GH2user** [comment]
Thanks for the quick reply @azogue. That's what I thought.

Now you are just copying one value into the new sensor state.
How about creating a new state which could be an existing value in the data or build up from other values in the data.
new sensor state = command (above example result: flip) current implementation
new sensor state = command.flip_degrees.activated_face  ( above example result: flip.90.2 )

That means a lot of parsing in your code but gives tremendous flexibility I think.
Anyway will wait for you to get the cube and see how you want to tackle it, template sensor might be the way to go.

**Comment by azogue** [comment]
I could try to implement something like:

```yaml
sensor:
  - platform: eventsensor
    name: Last aqara cube action
    event: zha_event
    state: "command, args.flip_degrees, args.activated_face"
    event_data:
      unique_id: "00:15:8d:00:04:21:53:9b:2:0x0012"
    state_map:
      flip_90_2: "FLIP: 90º, FACE 2"
      # ...
```

By using commas to introduce more than one key to generate the state, and then extract all and join with spaces or '_', so for the example above the state would be **"flip_90_2"**, which could be also mapped to any custom state.

But I'm not sure if it is a good idea to add that extra complexity, as, anyway, any implementation done here will be always **less powerful than what can be accomplished with a custom template**:

```yaml
sensor:
  - platform: template
    sensors:
      aqara_cube_action:
        value_template: >
          {%- if (states.sensor.last_aqara_cube_action.state != 'unknown') %}
          {% set attrs = states.sensor.last_aqara_cube_action.attributes %}
          {{ attrs.command | upper }}: {{ attrs.args.flip_degrees }}º, FACE {{ attrs.args.activated_face }}
          {% else %}
          {{ states.sensor.last_aqara_cube_action.state }}
          {% endif -%}
        
        entity_id:
          - sensor.last_aqara_cube_action
```

I'll wait for the cube to arrive so I can put my hands on it. 

It was a compulsive purchase :), I don't know yet how I'm going to use it, but I'm very curious about it, is it reliable?
